// import Provider from '@/context/Provider.js';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      {/* <Provider> */}
        <body>{children}</body>
      {/* </Provider> */}
    </html>
  )
}
